// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/contracts": {
            "get": {
                "description": "Returns all contracts.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "contracts"
                ],
                "summary": "List contracts",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/subscriber-service_service_contract.Contract"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/gorouter.ErrorResponse"
                        }
                    }
                }
            },
            "post": {
                "description": "Creates a contract between subscriber and metering object.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "contracts"
                ],
                "summary": "Create contract",
                "parameters": [
                    {
                        "description": "Contract creation payload",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/contract.AddContractRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/subscriber-service_service_contract.Contract"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/gorouter.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/gorouter.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/contracts/objects/{objectID}/last": {
            "get": {
                "description": "Returns the latest contract for a metering object.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "contracts"
                ],
                "summary": "Get latest object contract",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Object ID",
                        "name": "objectID",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/subscriber-service_service_contract.Contract"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/gorouter.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/gorouter.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/gorouter.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/objects": {
            "get": {
                "description": "Returns all metering objects.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "objects"
                ],
                "summary": "List objects",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/subscriber-service_service_object.Object"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/gorouter.ErrorResponse"
                        }
                    }
                }
            },
            "post": {
                "description": "Creates a metering object with devices and seals.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "objects"
                ],
                "summary": "Create metering object",
                "parameters": [
                    {
                        "description": "Object creation payload",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/object.AddObjectRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/subscriber-service_service_object.Object"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/gorouter.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/gorouter.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/objects/devices/{deviceID}": {
            "get": {
                "description": "Returns a metering object containing the specified device.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "objects"
                ],
                "summary": "Get object by device ID",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Device ID",
                        "name": "deviceID",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/subscriber-service_service_object.Object"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/gorouter.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/gorouter.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/gorouter.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/objects/seals/{sealID}": {
            "get": {
                "description": "Returns a metering object containing the specified seal.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "objects"
                ],
                "summary": "Get object by seal ID",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Seal ID",
                        "name": "sealID",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/subscriber-service_service_object.Object"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/gorouter.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/gorouter.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/gorouter.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/objects/{id}": {
            "get": {
                "description": "Returns a metering object by identifier.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "objects"
                ],
                "summary": "Get object by ID",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Object ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/subscriber-service_service_object.Object"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/gorouter.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/gorouter.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/gorouter.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/registry/parse": {
            "post": {
                "description": "Parses an Excel registry and imports subscribers, objects, devices, seals, and contracts.",
                "consumes": [
                    "multipart/form-data"
                ],
                "tags": [
                    "registry"
                ],
                "summary": "Import registry",
                "parameters": [
                    {
                        "type": "file",
                        "description": "Registry Excel file",
                        "name": "File",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/gorouter.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/gorouter.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/subscribers": {
            "get": {
                "description": "Returns all subscribers.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "subscribers"
                ],
                "summary": "List subscribers",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/subscriber-service_service_subscriber.Subscriber"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/gorouter.ErrorResponse"
                        }
                    }
                }
            },
            "post": {
                "description": "Creates a subscriber with passport data.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "subscribers"
                ],
                "summary": "Create subscriber",
                "parameters": [
                    {
                        "description": "Subscriber creation payload",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/subscriber.AddSubscriberRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/subscriber-service_service_subscriber.Subscriber"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/gorouter.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/gorouter.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/subscribers/{id}": {
            "get": {
                "description": "Returns subscriber data by identifier.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "subscribers"
                ],
                "summary": "Get subscriber by ID",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Subscriber ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/subscriber-service_service_subscriber.Subscriber"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/gorouter.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/gorouter.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/gorouter.ErrorResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "contract.AddContractRequest": {
            "type": "object",
            "properties": {
                "Number": {
                    "type": "string"
                },
                "ObjectID": {
                    "type": "integer"
                },
                "SignDate": {
                    "type": "string"
                },
                "SubscriberID": {
                    "type": "integer"
                }
            }
        },
        "gorouter.ErrorInfo": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "string"
                },
                "message": {
                    "type": "string"
                }
            }
        },
        "gorouter.ErrorResponse": {
            "type": "object",
            "properties": {
                "error": {
                    "$ref": "#/definitions/gorouter.ErrorInfo"
                }
            }
        },
        "object.AddObjectRequest": {
            "type": "object",
            "properties": {
                "Address": {
                    "type": "string"
                },
                "Devices": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/object.AddObjectRequestDevice"
                    }
                },
                "HaveAutomaton": {
                    "type": "boolean"
                }
            }
        },
        "object.AddObjectRequestDevice": {
            "type": "object",
            "properties": {
                "Number": {
                    "type": "string"
                },
                "PlaceDescription": {
                    "type": "string"
                },
                "PlaceType": {
                    "$ref": "#/definitions/object.DevicePlaceType"
                },
                "Seals": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/object.AddObjectRequestSeal"
                    }
                },
                "Type": {
                    "type": "string"
                }
            }
        },
        "object.AddObjectRequestSeal": {
            "type": "object",
            "properties": {
                "Number": {
                    "type": "string"
                },
                "Place": {
                    "type": "string"
                }
            }
        },
        "object.DevicePlaceType": {
            "type": "integer",
            "enum": [
                0,
                1,
                2,
                3
            ],
            "x-enum-varnames": [
                "DevicePlaceUnknown",
                "DevicePlaceOther",
                "DevicePlaceFlat",
                "DevicePlaceStairLanding"
            ]
        },
        "subscriber-service_service_contract.Contract": {
            "type": "object",
            "properties": {
                "CreatedAt": {
                    "type": "string"
                },
                "ID": {
                    "type": "integer"
                },
                "Number": {
                    "type": "string"
                },
                "Object": {
                    "$ref": "#/definitions/subscriber-service_service_object.Object"
                },
                "SignDate": {
                    "type": "string"
                },
                "Subscriber": {
                    "$ref": "#/definitions/subscriber-service_service_subscriber.Subscriber"
                },
                "UpdatedAt": {
                    "type": "string"
                }
            }
        },
        "subscriber-service_service_object.Device": {
            "type": "object",
            "properties": {
                "CreatedAt": {
                    "type": "string"
                },
                "ID": {
                    "type": "integer"
                },
                "Number": {
                    "type": "string"
                },
                "ObjectID": {
                    "type": "integer"
                },
                "PlaceDescription": {
                    "type": "string"
                },
                "PlaceType": {
                    "$ref": "#/definitions/object.DevicePlaceType"
                },
                "Seals": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/subscriber-service_service_object.Seal"
                    }
                },
                "Type": {
                    "type": "string"
                },
                "UpdatedAt": {
                    "type": "string"
                }
            }
        },
        "subscriber-service_service_object.Object": {
            "type": "object",
            "properties": {
                "Address": {
                    "type": "string"
                },
                "CreatedAt": {
                    "type": "string"
                },
                "Devices": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/subscriber-service_service_object.Device"
                    }
                },
                "HaveAutomaton": {
                    "type": "boolean"
                },
                "ID": {
                    "type": "integer"
                },
                "UpdatedAt": {
                    "type": "string"
                }
            }
        },
        "subscriber-service_service_object.Seal": {
            "type": "object",
            "properties": {
                "CreatedAt": {
                    "type": "string"
                },
                "DeviceID": {
                    "type": "integer"
                },
                "ID": {
                    "type": "integer"
                },
                "Number": {
                    "type": "string"
                },
                "Place": {
                    "type": "string"
                },
                "UpdatedAt": {
                    "type": "string"
                }
            }
        },
        "subscriber-service_service_subscriber.Passport": {
            "type": "object",
            "properties": {
                "ID": {
                    "type": "integer"
                },
                "IssueDate": {
                    "type": "string"
                },
                "IssuedBy": {
                    "type": "string"
                },
                "Number": {
                    "type": "string"
                },
                "Series": {
                    "type": "string"
                }
            }
        },
        "subscriber-service_service_subscriber.Subscriber": {
            "type": "object",
            "properties": {
                "AccountNumber": {
                    "type": "string"
                },
                "BirthDate": {
                    "type": "string"
                },
                "CreatedAt": {
                    "type": "string"
                },
                "Email": {
                    "type": "string"
                },
                "ID": {
                    "type": "integer"
                },
                "INN": {
                    "type": "string"
                },
                "Name": {
                    "type": "string"
                },
                "Passport": {
                    "$ref": "#/definitions/subscriber-service_service_subscriber.Passport"
                },
                "Patronymic": {
                    "type": "string"
                },
                "PhoneNumber": {
                    "type": "string"
                },
                "Status": {
                    "$ref": "#/definitions/subscriber.Status"
                },
                "Surname": {
                    "type": "string"
                },
                "UpdatedAt": {
                    "type": "string"
                }
            }
        },
        "subscriber.AddSubscriberRequest": {
            "type": "object",
            "properties": {
                "AccountNumber": {
                    "type": "string"
                },
                "BirthDate": {
                    "type": "string"
                },
                "Email": {
                    "type": "string"
                },
                "INN": {
                    "type": "string"
                },
                "Name": {
                    "type": "string"
                },
                "Passport": {
                    "$ref": "#/definitions/subscriber.AddSubscriberRequestPassport"
                },
                "Patronymic": {
                    "type": "string"
                },
                "PhoneNumber": {
                    "type": "string"
                },
                "Surname": {
                    "type": "string"
                }
            }
        },
        "subscriber.AddSubscriberRequestPassport": {
            "type": "object",
            "properties": {
                "IssueDate": {
                    "type": "string"
                },
                "IssuedBy": {
                    "type": "string"
                },
                "Number": {
                    "type": "string"
                },
                "Series": {
                    "type": "string"
                }
            }
        },
        "subscriber.Status": {
            "type": "integer",
            "enum": [
                0,
                1,
                2,
                3
            ],
            "x-enum-varnames": [
                "StatusUnknown",
                "StatusActive",
                "StatusViolator",
                "StatusArchived"
            ]
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "/api/subscriber-service",
	Schemes:          []string{},
	Title:            "Subscriber Service API",
	Description:      "API for subscribers, metering objects, contracts, and registry import.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
