// Code generated by swaggo/swag. DO NOT EDIT.

package docs

import "github.com/swaggo/swag/v2"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "components": {
        "schemas": {
            "contract.AddContractRequest": {
                "properties": {
                    "Number": {
                        "type": "string"
                    },
                    "ObjectID": {
                        "type": "integer"
                    },
                    "SignDate": {
                        "type": "string"
                    },
                    "SubscriberID": {
                        "type": "integer"
                    }
                },
                "type": "object"
            },
            "gorouter.ErrorInfo": {
                "properties": {
                    "code": {
                        "type": "string"
                    },
                    "message": {
                        "type": "string"
                    }
                },
                "type": "object"
            },
            "gorouter.ErrorResponse": {
                "properties": {
                    "error": {
                        "$ref": "#/components/schemas/gorouter.ErrorInfo"
                    }
                },
                "type": "object"
            },
            "object.AddObjectRequest": {
                "properties": {
                    "Address": {
                        "type": "string"
                    },
                    "Devices": {
                        "items": {
                            "$ref": "#/components/schemas/object.AddObjectRequestDevice"
                        },
                        "type": "array",
                        "uniqueItems": false
                    },
                    "HaveAutomaton": {
                        "type": "boolean"
                    }
                },
                "type": "object"
            },
            "object.AddObjectRequestDevice": {
                "properties": {
                    "Number": {
                        "type": "string"
                    },
                    "PlaceDescription": {
                        "type": "string"
                    },
                    "PlaceType": {
                        "$ref": "#/components/schemas/object.DevicePlaceType"
                    },
                    "Seals": {
                        "items": {
                            "$ref": "#/components/schemas/object.AddObjectRequestSeal"
                        },
                        "type": "array",
                        "uniqueItems": false
                    },
                    "Type": {
                        "type": "string"
                    }
                },
                "type": "object"
            },
            "object.AddObjectRequestSeal": {
                "properties": {
                    "Number": {
                        "type": "string"
                    },
                    "Place": {
                        "type": "string"
                    }
                },
                "type": "object"
            },
            "object.DevicePlaceType": {
                "enum": [
                    0,
                    1,
                    2,
                    3
                ],
                "type": "integer",
                "x-enum-varnames": [
                    "DevicePlaceUnknown",
                    "DevicePlaceOther",
                    "DevicePlaceFlat",
                    "DevicePlaceStairLanding"
                ]
            },
            "subscriber-service_service_contract.Contract": {
                "properties": {
                    "CreatedAt": {
                        "type": "string"
                    },
                    "ID": {
                        "type": "integer"
                    },
                    "Number": {
                        "type": "string"
                    },
                    "Object": {
                        "$ref": "#/components/schemas/subscriber-service_service_object.Object"
                    },
                    "SignDate": {
                        "type": "string"
                    },
                    "Subscriber": {
                        "$ref": "#/components/schemas/subscriber-service_service_subscriber.Subscriber"
                    },
                    "UpdatedAt": {
                        "type": "string"
                    }
                },
                "type": "object"
            },
            "subscriber-service_service_object.Device": {
                "properties": {
                    "CreatedAt": {
                        "type": "string"
                    },
                    "ID": {
                        "type": "integer"
                    },
                    "Number": {
                        "type": "string"
                    },
                    "ObjectID": {
                        "type": "integer"
                    },
                    "PlaceDescription": {
                        "type": "string"
                    },
                    "PlaceType": {
                        "$ref": "#/components/schemas/object.DevicePlaceType"
                    },
                    "Seals": {
                        "items": {
                            "$ref": "#/components/schemas/subscriber-service_service_object.Seal"
                        },
                        "type": "array",
                        "uniqueItems": false
                    },
                    "Type": {
                        "type": "string"
                    },
                    "UpdatedAt": {
                        "type": "string"
                    }
                },
                "type": "object"
            },
            "subscriber-service_service_object.Object": {
                "properties": {
                    "Address": {
                        "type": "string"
                    },
                    "CreatedAt": {
                        "type": "string"
                    },
                    "Devices": {
                        "items": {
                            "$ref": "#/components/schemas/subscriber-service_service_object.Device"
                        },
                        "type": "array",
                        "uniqueItems": false
                    },
                    "HaveAutomaton": {
                        "type": "boolean"
                    },
                    "ID": {
                        "type": "integer"
                    },
                    "UpdatedAt": {
                        "type": "string"
                    }
                },
                "type": "object"
            },
            "subscriber-service_service_object.Seal": {
                "properties": {
                    "CreatedAt": {
                        "type": "string"
                    },
                    "DeviceID": {
                        "type": "integer"
                    },
                    "ID": {
                        "type": "integer"
                    },
                    "Number": {
                        "type": "string"
                    },
                    "Place": {
                        "type": "string"
                    },
                    "UpdatedAt": {
                        "type": "string"
                    }
                },
                "type": "object"
            },
            "subscriber-service_service_subscriber.Contract": {
                "properties": {
                    "CreatedAt": {
                        "type": "string"
                    },
                    "ID": {
                        "type": "integer"
                    },
                    "Number": {
                        "type": "string"
                    },
                    "ObjectID": {
                        "type": "integer"
                    },
                    "SignDate": {
                        "type": "string"
                    },
                    "UpdatedAt": {
                        "type": "string"
                    }
                },
                "type": "object"
            },
            "subscriber-service_service_subscriber.Passport": {
                "properties": {
                    "ID": {
                        "type": "integer"
                    },
                    "IssueDate": {
                        "type": "string"
                    },
                    "IssuedBy": {
                        "type": "string"
                    },
                    "Number": {
                        "type": "string"
                    },
                    "Series": {
                        "type": "string"
                    }
                },
                "type": "object"
            },
            "subscriber-service_service_subscriber.Subscriber": {
                "properties": {
                    "AccountNumber": {
                        "type": "string"
                    },
                    "BirthDate": {
                        "type": "string"
                    },
                    "CreatedAt": {
                        "type": "string"
                    },
                    "Email": {
                        "type": "string"
                    },
                    "ID": {
                        "type": "integer"
                    },
                    "INN": {
                        "type": "string"
                    },
                    "Name": {
                        "type": "string"
                    },
                    "Passport": {
                        "$ref": "#/components/schemas/subscriber-service_service_subscriber.Passport"
                    },
                    "Patronymic": {
                        "type": "string"
                    },
                    "PhoneNumber": {
                        "type": "string"
                    },
                    "Status": {
                        "$ref": "#/components/schemas/subscriber.Status"
                    },
                    "Surname": {
                        "type": "string"
                    },
                    "UpdatedAt": {
                        "type": "string"
                    }
                },
                "type": "object"
            },
            "subscriber.AddSubscriberRequest": {
                "properties": {
                    "AccountNumber": {
                        "type": "string"
                    },
                    "BirthDate": {
                        "type": "string"
                    },
                    "Email": {
                        "type": "string"
                    },
                    "INN": {
                        "type": "string"
                    },
                    "Name": {
                        "type": "string"
                    },
                    "Passport": {
                        "$ref": "#/components/schemas/subscriber.AddSubscriberRequestPassport"
                    },
                    "Patronymic": {
                        "type": "string"
                    },
                    "PhoneNumber": {
                        "type": "string"
                    },
                    "Surname": {
                        "type": "string"
                    }
                },
                "type": "object"
            },
            "subscriber.AddSubscriberRequestPassport": {
                "properties": {
                    "IssueDate": {
                        "type": "string"
                    },
                    "IssuedBy": {
                        "type": "string"
                    },
                    "Number": {
                        "type": "string"
                    },
                    "Series": {
                        "type": "string"
                    }
                },
                "type": "object"
            },
            "subscriber.ExtendedSubscriber": {
                "properties": {
                    "Contracts": {
                        "items": {
                            "$ref": "#/components/schemas/subscriber-service_service_subscriber.Contract"
                        },
                        "type": "array",
                        "uniqueItems": false
                    },
                    "Objects": {
                        "items": {
                            "$ref": "#/components/schemas/subscriber-service_service_object.Object"
                        },
                        "type": "array",
                        "uniqueItems": false
                    },
                    "Subscriber": {
                        "$ref": "#/components/schemas/subscriber-service_service_subscriber.Subscriber"
                    }
                },
                "type": "object"
            },
            "subscriber.Status": {
                "enum": [
                    0,
                    1,
                    2,
                    3
                ],
                "type": "integer",
                "x-enum-varnames": [
                    "StatusUnknown",
                    "StatusActive",
                    "StatusViolator",
                    "StatusArchived"
                ]
            }
        }
    },
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "version": "{{.Version}}"
    },
    "externalDocs": {
        "description": "",
        "url": ""
    },
    "paths": {
        "/contracts": {
            "get": {
                "description": "Returns all contracts.",
                "parameters": [
                    {
                        "description": "Maximum number of items to return; 0 means no limit",
                        "in": "query",
                        "name": "limit",
                        "schema": {
                            "type": "integer"
                        }
                    },
                    {
                        "description": "Number of items to skip",
                        "in": "query",
                        "name": "offset",
                        "schema": {
                            "type": "integer"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "items": {
                                        "$ref": "#/components/schemas/subscriber-service_service_contract.Contract"
                                    },
                                    "type": "array"
                                }
                            }
                        },
                        "description": "OK"
                    },
                    "400": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/gorouter.ErrorResponse"
                                }
                            }
                        },
                        "description": "Bad Request"
                    },
                    "500": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/gorouter.ErrorResponse"
                                }
                            }
                        },
                        "description": "Internal Server Error"
                    }
                },
                "summary": "List contracts",
                "tags": [
                    "contracts"
                ]
            },
            "post": {
                "description": "Creates a contract between subscriber and metering object.",
                "requestBody": {
                    "content": {
                        "application/json": {
                            "schema": {
                                "$ref": "#/components/schemas/contract.AddContractRequest",
                                "summary": "request",
                                "description": "Contract creation payload"
                            }
                        }
                    },
                    "description": "Contract creation payload",
                    "required": true
                },
                "responses": {
                    "200": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/subscriber-service_service_contract.Contract"
                                }
                            }
                        },
                        "description": "OK"
                    },
                    "400": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/gorouter.ErrorResponse"
                                }
                            }
                        },
                        "description": "Bad Request"
                    },
                    "500": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/gorouter.ErrorResponse"
                                }
                            }
                        },
                        "description": "Internal Server Error"
                    }
                },
                "summary": "Create contract",
                "tags": [
                    "contracts"
                ]
            }
        },
        "/contracts/objects/last": {
            "get": {
                "description": "Returns latest contracts for several metering objects.",
                "parameters": [
                    {
                        "description": "Object IDs",
                        "in": "query",
                        "name": "id",
                        "required": true,
                        "schema": {
                            "items": {
                                "type": "integer"
                            },
                            "type": "array"
                        },
                        "style": "form"
                    }
                ],
                "responses": {
                    "200": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "items": {
                                        "$ref": "#/components/schemas/subscriber-service_service_contract.Contract"
                                    },
                                    "type": "array"
                                }
                            }
                        },
                        "description": "OK"
                    },
                    "400": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/gorouter.ErrorResponse"
                                }
                            }
                        },
                        "description": "Bad Request"
                    },
                    "500": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/gorouter.ErrorResponse"
                                }
                            }
                        },
                        "description": "Internal Server Error"
                    }
                },
                "summary": "Get latest object contracts",
                "tags": [
                    "contracts"
                ]
            }
        },
        "/contracts/objects/{objectID}/last": {
            "get": {
                "description": "Returns the latest contract for a metering object.",
                "parameters": [
                    {
                        "description": "Object ID",
                        "in": "path",
                        "name": "objectID",
                        "required": true,
                        "schema": {
                            "type": "integer"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/subscriber-service_service_contract.Contract"
                                }
                            }
                        },
                        "description": "OK"
                    },
                    "400": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/gorouter.ErrorResponse"
                                }
                            }
                        },
                        "description": "Bad Request"
                    },
                    "404": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/gorouter.ErrorResponse"
                                }
                            }
                        },
                        "description": "Not Found"
                    },
                    "500": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/gorouter.ErrorResponse"
                                }
                            }
                        },
                        "description": "Internal Server Error"
                    }
                },
                "summary": "Get latest object contract",
                "tags": [
                    "contracts"
                ]
            }
        },
        "/objects": {
            "get": {
                "description": "Returns all metering objects.",
                "parameters": [
                    {
                        "description": "Maximum number of items to return; 0 means no limit",
                        "in": "query",
                        "name": "limit",
                        "schema": {
                            "type": "integer"
                        }
                    },
                    {
                        "description": "Number of items to skip",
                        "in": "query",
                        "name": "offset",
                        "schema": {
                            "type": "integer"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "items": {
                                        "$ref": "#/components/schemas/subscriber-service_service_object.Object"
                                    },
                                    "type": "array"
                                }
                            }
                        },
                        "description": "OK"
                    },
                    "400": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/gorouter.ErrorResponse"
                                }
                            }
                        },
                        "description": "Bad Request"
                    },
                    "500": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/gorouter.ErrorResponse"
                                }
                            }
                        },
                        "description": "Internal Server Error"
                    }
                },
                "summary": "List objects",
                "tags": [
                    "objects"
                ]
            },
            "post": {
                "description": "Creates a metering object with devices and seals.",
                "requestBody": {
                    "content": {
                        "application/json": {
                            "schema": {
                                "$ref": "#/components/schemas/object.AddObjectRequest",
                                "summary": "request",
                                "description": "Object creation payload"
                            }
                        }
                    },
                    "description": "Object creation payload",
                    "required": true
                },
                "responses": {
                    "200": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/subscriber-service_service_object.Object"
                                }
                            }
                        },
                        "description": "OK"
                    },
                    "400": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/gorouter.ErrorResponse"
                                }
                            }
                        },
                        "description": "Bad Request"
                    },
                    "500": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/gorouter.ErrorResponse"
                                }
                            }
                        },
                        "description": "Internal Server Error"
                    }
                },
                "summary": "Create metering object",
                "tags": [
                    "objects"
                ]
            }
        },
        "/objects/devices/{deviceID}": {
            "get": {
                "description": "Returns a metering object containing the specified device.",
                "parameters": [
                    {
                        "description": "Device ID",
                        "in": "path",
                        "name": "deviceID",
                        "required": true,
                        "schema": {
                            "type": "integer"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/subscriber-service_service_object.Object"
                                }
                            }
                        },
                        "description": "OK"
                    },
                    "400": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/gorouter.ErrorResponse"
                                }
                            }
                        },
                        "description": "Bad Request"
                    },
                    "404": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/gorouter.ErrorResponse"
                                }
                            }
                        },
                        "description": "Not Found"
                    },
                    "500": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/gorouter.ErrorResponse"
                                }
                            }
                        },
                        "description": "Internal Server Error"
                    }
                },
                "summary": "Get object by device ID",
                "tags": [
                    "objects"
                ]
            }
        },
        "/objects/seals/{sealID}": {
            "get": {
                "description": "Returns a metering object containing the specified seal.",
                "parameters": [
                    {
                        "description": "Seal ID",
                        "in": "path",
                        "name": "sealID",
                        "required": true,
                        "schema": {
                            "type": "integer"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/subscriber-service_service_object.Object"
                                }
                            }
                        },
                        "description": "OK"
                    },
                    "400": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/gorouter.ErrorResponse"
                                }
                            }
                        },
                        "description": "Bad Request"
                    },
                    "404": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/gorouter.ErrorResponse"
                                }
                            }
                        },
                        "description": "Not Found"
                    },
                    "500": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/gorouter.ErrorResponse"
                                }
                            }
                        },
                        "description": "Internal Server Error"
                    }
                },
                "summary": "Get object by seal ID",
                "tags": [
                    "objects"
                ]
            }
        },
        "/objects/{id}": {
            "get": {
                "description": "Returns a metering object by identifier.",
                "parameters": [
                    {
                        "description": "Object ID",
                        "in": "path",
                        "name": "id",
                        "required": true,
                        "schema": {
                            "type": "integer"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/subscriber-service_service_object.Object"
                                }
                            }
                        },
                        "description": "OK"
                    },
                    "400": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/gorouter.ErrorResponse"
                                }
                            }
                        },
                        "description": "Bad Request"
                    },
                    "404": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/gorouter.ErrorResponse"
                                }
                            }
                        },
                        "description": "Not Found"
                    },
                    "500": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/gorouter.ErrorResponse"
                                }
                            }
                        },
                        "description": "Internal Server Error"
                    }
                },
                "summary": "Get object by ID",
                "tags": [
                    "objects"
                ]
            }
        },
        "/registry/parse": {
            "post": {
                "description": "Parses an Excel registry and imports subscribers, objects, devices, seals, and contracts.",
                "requestBody": {
                    "content": {
                        "application/x-www-form-urlencoded": {
                            "schema": {
                                "title": "File",
                                "type": "file"
                            }
                        },
                        "multipart/form-data": {
                            "schema": {
                                "type": "object"
                            }
                        }
                    },
                    "description": "Registry Excel file",
                    "required": true
                },
                "responses": {
                    "200": {
                        "description": "OK"
                    },
                    "400": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/gorouter.ErrorResponse"
                                }
                            }
                        },
                        "description": "Bad Request"
                    },
                    "500": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/gorouter.ErrorResponse"
                                }
                            }
                        },
                        "description": "Internal Server Error"
                    }
                },
                "summary": "Import registry",
                "tags": [
                    "registry"
                ]
            }
        },
        "/subscribers": {
            "get": {
                "description": "Returns all subscribers.",
                "parameters": [
                    {
                        "description": "Maximum number of items to return; 0 means no limit",
                        "in": "query",
                        "name": "limit",
                        "schema": {
                            "type": "integer"
                        }
                    },
                    {
                        "description": "Number of items to skip",
                        "in": "query",
                        "name": "offset",
                        "schema": {
                            "type": "integer"
                        }
                    },
                    {
                        "description": "Search by subscriber surname",
                        "in": "query",
                        "name": "surname",
                        "schema": {
                            "type": "string"
                        }
                    },
                    {
                        "description": "Search by subscriber name",
                        "in": "query",
                        "name": "name",
                        "schema": {
                            "type": "string"
                        }
                    },
                    {
                        "description": "Search by subscriber patronymic",
                        "in": "query",
                        "name": "patronymic",
                        "schema": {
                            "type": "string"
                        }
                    },
                    {
                        "description": "Search by subscriber account number",
                        "in": "query",
                        "name": "accountNumber",
                        "schema": {
                            "type": "string"
                        }
                    },
                    {
                        "description": "Search by subscriber phone number",
                        "in": "query",
                        "name": "phoneNumber",
                        "schema": {
                            "type": "string"
                        }
                    },
                    {
                        "description": "Search by metering object address",
                        "in": "query",
                        "name": "address",
                        "schema": {
                            "type": "string"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "items": {
                                        "$ref": "#/components/schemas/subscriber-service_service_subscriber.Subscriber"
                                    },
                                    "type": "array"
                                }
                            }
                        },
                        "description": "OK"
                    },
                    "400": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/gorouter.ErrorResponse"
                                }
                            }
                        },
                        "description": "Bad Request"
                    },
                    "500": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/gorouter.ErrorResponse"
                                }
                            }
                        },
                        "description": "Internal Server Error"
                    }
                },
                "summary": "List subscribers",
                "tags": [
                    "subscribers"
                ]
            },
            "post": {
                "description": "Creates a subscriber with passport data.",
                "requestBody": {
                    "content": {
                        "application/json": {
                            "schema": {
                                "$ref": "#/components/schemas/subscriber.AddSubscriberRequest",
                                "summary": "request",
                                "description": "Subscriber creation payload"
                            }
                        }
                    },
                    "description": "Subscriber creation payload",
                    "required": true
                },
                "responses": {
                    "200": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/subscriber-service_service_subscriber.Subscriber"
                                }
                            }
                        },
                        "description": "OK"
                    },
                    "400": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/gorouter.ErrorResponse"
                                }
                            }
                        },
                        "description": "Bad Request"
                    },
                    "500": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/gorouter.ErrorResponse"
                                }
                            }
                        },
                        "description": "Internal Server Error"
                    }
                },
                "summary": "Create subscriber",
                "tags": [
                    "subscribers"
                ]
            }
        },
        "/subscribers/{id}": {
            "get": {
                "description": "Returns subscriber data by identifier.",
                "parameters": [
                    {
                        "description": "Subscriber ID",
                        "in": "path",
                        "name": "id",
                        "required": true,
                        "schema": {
                            "type": "integer"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/subscriber-service_service_subscriber.Subscriber"
                                }
                            }
                        },
                        "description": "OK"
                    },
                    "400": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/gorouter.ErrorResponse"
                                }
                            }
                        },
                        "description": "Bad Request"
                    },
                    "404": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/gorouter.ErrorResponse"
                                }
                            }
                        },
                        "description": "Not Found"
                    },
                    "500": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/gorouter.ErrorResponse"
                                }
                            }
                        },
                        "description": "Internal Server Error"
                    }
                },
                "summary": "Get subscriber by ID",
                "tags": [
                    "subscribers"
                ]
            }
        },
        "/subscribers/{id}/extended": {
            "get": {
                "description": "Returns subscriber data with all related contracts and objects.",
                "parameters": [
                    {
                        "description": "Subscriber ID",
                        "in": "path",
                        "name": "id",
                        "required": true,
                        "schema": {
                            "type": "integer"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/subscriber.ExtendedSubscriber"
                                }
                            }
                        },
                        "description": "OK"
                    },
                    "400": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/gorouter.ErrorResponse"
                                }
                            }
                        },
                        "description": "Bad Request"
                    },
                    "404": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/gorouter.ErrorResponse"
                                }
                            }
                        },
                        "description": "Not Found"
                    },
                    "500": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/gorouter.ErrorResponse"
                                }
                            }
                        },
                        "description": "Internal Server Error"
                    }
                },
                "summary": "Get subscriber with contracts and objects",
                "tags": [
                    "subscribers"
                ]
            }
        }
    },
    "openapi": "3.1.0",
    "servers": [
        {
            "url": "/api/subscriber-service"
        }
    ]
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Title:            "Subscriber Service API",
	Description:      "API for subscribers, metering objects, contracts, and registry import.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
